### ISSUE TITLE
Extension is difficult to find when using built-in VS Code search

### ISSUE THREAD

**Issue by marcinsmialek** [cwan/native-ascii-converter#15]
This is a great extension, but I couldn't find it from inside of VS Code.

Fortunately DuckDuckGo listed it as a top result for both:
- vs code convert u symbol to Unicode
- vs code Unicode escapes convert

If you could add "Unicode" in the name, then it would be much easier to discover, especially for people not familiar with Java.
I'd also suggest adding "Unicode" tag.

Thanks!

**Comment by cwan** [comment]
Thanks for the advice!

> If you could add "Unicode" in the name,

Sorry, I don't want to change the extension name because it is a proper noun.

> I'd also suggest adding "Unicode" tag.

"Unicode" tag has been added.

Regards,
