### ISSUE TITLE
AutoConversionOnActivate can't work, when suffix isn't "properties"

### ISSUE THREAD

**Issue by liangjiancang** [cwan/native-ascii-converter#9]
Can not work with properties with other suffix, like "build.properties.prod".
Please use "files.associations" to detect a file whether a "properties" file, instead of its suffix.

**Comment by liangjiancang** [comment]
Both "native-ascii-converter.auto-conversion-on-activate" and "native-ascii-converter.auto-conversion-on-save" have this problem.

**Comment by cwan** [comment]
Thank you for your comments.
I'll try it.

**Comment by cwan** [comment]
@liangjiancang 
I fixed this issue and release ver.1.0.6.

Set the configuration `native-ascii-converter.use-files.associations` to true, and write setting.json as follows:

```json
{
  "files.associations": {
    "*.properties": "properties",
    "*.properties.prod": "properties"
  }
}
```

**Comment by liangjiancang** [comment]
Thank you. And I find that `{ "*.properties.*": "properties" }` may be a better choice.
